import { FieldSchema } from '@/modules/client/components/DynamicForm';

export const optionsTags = [
  'security',
  'audit',
  'backend',
  'frontend',
  'refactor',
  'documentation',
  'API',
  'database',
  'migration',
  'UI',
  'UX',
  'design',
];

export const formSchemaFromApi: FieldSchema[] = [
  {
    name: 'title',
    label: 'Title',
    type: 'text',
    required: true,
    order: 1,
    placeholder: 'Input title',
    options: [],
  },
  {
    name: 'organizationId',
    label: 'Organization',
    type: 'select',
    required: true,
    order: 2,
    placeholder: '',
    options: [],
  },
  {
    name: 'status',
    label: 'Status',
    type: 'select',
    options: ['todo', 'in-progress', 'completed'],
    required: true,
    order: 3,
    placeholder: '',
  },
  {
    name: 'description',
    label: 'Description',
    type: 'textarea',
    placeholder: 'Input description',
    order: 7,
    options: [],
    required: false,
  },
  {
    name: 'priority',
    label: 'Priority',
    type: 'select',
    options: ['low', 'medium', 'high'],
    order: 6,
    required: false,
    placeholder: '',
  },
  {
    name: 'dueDate',
    label: 'Due Date',
    type: 'date',
    order: 5,
    required: false,
    placeholder: '',
    options: [],
  },
  {
    name: 'tags',
    label: 'Tags',
    type: 'tagpicker',
    required: true,
    options: [
      'security',
      'audit',
      'backend',
      'frontend',
      'refactor',
      'documentation',
      'API',
      'database',
      'migration',
      'UI',
      'UX',
      'design',
    ],
    order: 4,
    placeholder: '',
  },
];
